apiVersion: extensions/v1alpha1
kind: ExtendedResource
metadata:
  name: er7
  labels:
    app: er7
spec:
  properties:
    type: k80
  rawResourceName: nvidia.com/gpu
  deviceID: gpu7
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: 
            - 127.0.0.1